# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/liangxiaoshi666/android_kernel_xiaomi_sdm660
          kernel-dir: msm-4.4
          kernel-branch: 11-EAS
          config: clover_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/rsuntk/KernelSU
          ksu-version: main
          android-version: 11
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
